### PR TITLE
Vacation's affect on minimum hours per pay period

### PR DESCRIPTION
**Pull request by nmorduch**

### CODE REVIEW

**Comment by harrislapiroff** [comment]
:+1:

**Comment by melinath** [comment]
+1

**Comment by nmorduch** [comment]
OH MY GOD I USED AFFECT INSTEAD OF EFFECT
MERGING ANYWAY THOUGH
+1

**Comment by melinath** [comment]
yeah... I didn't want to say anything...

**Comment by harrislapiroff** [comment]
I thought maybe the typo was including the word "on"

**Comment by harrislapiroff** [comment]
wait no, that doesn't work. the apostrophe would have to be a typo too.

**Pull request merged**
