### PR TITLE
Remove base rate from policies

### PR DESCRIPTION
**Pull request by nmorduch**

### CODE REVIEW

**Comment by harrislapiroff** [comment]
+1 as is, but also I might propose just cutting the sentence altogether. It doesn't really add any information to the document as it stands.

**Comment by harrislapiroff** [comment]
Also wow we have not been putting emergency hours into our contracts.

**Comment by nmorduch** [comment]
It felt weird to refer to rates based on the base rate without referring to the base rate. But I guess they're there anyway. :+1: to an alternate option removing the line altogether.

**Comment by melinath** [comment]
+1 on either version.

**Comment by nmorduch** [comment]
I'll remove the line, just on master.

**Comment by nmorduch** [comment]
Actually I'm gonna do it on this branch...

**Pull request merged**
